name: Rust

on:
  push:
    branches:
    # - main
    - master
    - release/*
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose

  create-release:
    if: github.ref == 'refs/heads/master'  # This job runs only for pushes to master
    needs: build  # Ensure this runs after the build job
    runs-on: ubuntu-latest  # Runs on a Linux runner
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Uses the GITHUB_TOKEN for authorization
      with:
        tag_name: ${{ github.sha }}
        release_name: Release ${{ github.sha }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}  # This is the upload URL for the assets
        asset_path: ./target/debug/your_project_name.exe  # Adjust the path as needed
        asset_name: your_project_name.exe
        asset_content_type: application/octet-stream
