name: Rust

on:
  push:
    branches:
    - main
    - master  # Assuming you want releases on pushes to master.
    - release/*
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.5
    - name: Build
      run: cargo build --verbose
      # Assuming this generates an executable or other output in 'target/debug/'

  release:
    needs: build
    if: github.ref == 'refs/heads/master'  # Run this job only for pushes to master
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.5
    - name: Download artifact
      uses: actions/download-artifact@v4.1.7
      with:
        name: mon-artifact  # Replace with the name of your build artifact
        path: /artifacts/  # Replace with the path where to store the artifact

    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v2.0.5
      with:
        files: /artifacts/mon-artifact  # Adjust this path to where your build outputs are stored
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
